-- MySQL Script generated by MySQL Workbench
-- Sat Jul  3 18:52:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema foodorderapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foodorderapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foodorderapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `foodorderapp` ;

-- -----------------------------------------------------
-- Table `foodorderapp`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`address` (
  `addressid` INT NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `zipcode` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`addressid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`customer` (
  `customer_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `UK_dwk6cx0afu8bs9o4t536v1j5v` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`cart` (
  `food_id` INT NOT NULL,
  `food_category` VARCHAR(255) NOT NULL,
  `food_name` VARCHAR(255) NOT NULL,
  `food_price` DOUBLE NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `customer_customer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `FK9hpirec8qm60sghwjqvu0s6ic` (`customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `FK9hpirec8qm60sghwjqvu0s6ic`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `foodorderapp`.`customer` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`restuarant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`restuarant` (
  `restuarant_id` INT NOT NULL,
  `restuarant_location` VARCHAR(255) NOT NULL,
  `restuarant_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`restuarant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`menu` (
  `food_id` INT NOT NULL,
  `food_category` VARCHAR(255) NOT NULL,
  `food_name` VARCHAR(255) NOT NULL,
  `food_price` DOUBLE NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `restuarant_restuarant_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `FKrtuntt1c7q091o3e3fqhromhy` (`restuarant_restuarant_id` ASC) VISIBLE,
  CONSTRAINT `FKrtuntt1c7q091o3e3fqhromhy`
    FOREIGN KEY (`restuarant_restuarant_id`)
    REFERENCES `foodorderapp`.`restuarant` (`restuarant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`order_details` (
  `orderid` INT NOT NULL,
  `totalprice` INT NULL DEFAULT NULL,
  `totalquantity` INT NULL DEFAULT NULL,
  `address_addressid` INT NULL DEFAULT NULL,
  `customer_customer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `FKi8ttmd0pmwdsh0fm6ginjq5xi` (`address_addressid` ASC) VISIBLE,
  INDEX `FK4hxtiln4qsyv0bkrns6n1r2f1` (`customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `FK4hxtiln4qsyv0bkrns6n1r2f1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `foodorderapp`.`customer` (`customer_id`),
  CONSTRAINT `FKi8ttmd0pmwdsh0fm6ginjq5xi`
    FOREIGN KEY (`address_addressid`)
    REFERENCES `foodorderapp`.`address` (`addressid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `foodorderapp`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodorderapp`.`state` (
  `state_id` INT NOT NULL,
  `state_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
